name: BlogsNuxt

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - CHANGELOG.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      # 拉取代码
      - name: checkOut code
        uses: actions/checkout@v1 # 第一步，下载代码仓库

      # 推到服务器
      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.BLOGS_PC_DEPLOY_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SERVER_ROOT_NAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/admin/blogs-nuxt/ # 部署到目标文件夹
      # 使用PM2 重启服务
      - name: Restart server # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 下面三个配置与上一步类似
          username: ${{ secrets.SERVER_ROOT_NAME }}
          key: ${{ secrets.BLOGS_PC_DEPLOY_KEY }}
          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
          # cd /home/admin/blogs-nuxt
          script: |
            pm2 restart 1
