name: BlogsNuxt

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - CHANGELOG.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      # 第一步：下载源码（CI/CD拉取代码到自己的本地）
      - name: Checkout
        uses: actions/checkout@master
      # 第二步：打包构建
      - name: Build
        uses: actions/setup-node@master
      - scripts: |
          npm install --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
          npm run build 
          tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json
      # 压缩打包后的代码到release.tgz
      # 第三步部署到服务器
      - name: Deploy # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          port: "22"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_ROOT_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.BLOGS_PC_DEPLOY_KEY }}
          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
          # cd /home/admin/blogs-nuxt
          script: |
            cd /home/admin/blogs-nuxt
            mkdir demo
