name: Deploy static files

on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - CHANGELOG.md
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Yarn
        run: npm i -g yarn
      - name: Build
        run: yarn config set registry https://registry.npm.taobao.org && yarn config set disturl https://npm.taobao.org/dist && yarn config set sass-binary-site http://npm.taobao.org/mirrors/node-sass && yarn install && yarn run build
        env:
          CI: true
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@master
        env:
          DEPLOY_KEY: ${{ secrets.BLOGS_PC_DEPLOY_KEY }}
          # ARGS: -avz --delete --include='cards/' --include='css/' --include='js/' --include='images/'
          #   --include='iconfont/' --include="robots.txt" --include='dist/' --exclude='/*'
          FOLDER: ./
          SERVER_PORT: "22"
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /home/admin/blogs-nuxt/
      - name: Restart Server
        uses: AEnterprise/rsync-deploy@master
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: -avz
          FOLDER: ./
          SERVER_PORT: "22"
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /home/admin/blogs-nuxt/
